[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

  #[[plugins]]
  #repo = 'Shougo/deoplete.nvim'
  #on_event = 'InsertEnter'
  #hook_add = '''
  #source ~/.config/nvim/plugins/deoplete.vim
  #call dein#remote_plugins()
  #'''
